---
title: "HW2"
author: "Roman Smirnov"
date: "4/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(glue)
setwd('~/ITMO_EDUCATION/second_term/R/HWs/HW2')
deck <- read.csv('deck.csv')
# head(deck)
```

##1.create suitable objects for casino deck, dealer hand, and your hand

```{r}
### 0) create suitable objects for casino deck, dealer hand, and your hand.
deck <- do.call('rbind', list(deck, deck, deck, deck))

player_hand <- data.frame(matrix(ncol=3, nrow=0, 
                  dimnames=list(NULL, c("face",  "suit",  "value"))))

dealer_hand<- data.frame(matrix(ncol=3, nrow=0, 
                  dimnames=list(NULL, c("face",  "suit",  "value"))))
mixed <- deck
```

##2.implement shuffle_deck() function

```{r}
### 1) implement shuffle_deck() function
shuffle_deck <-  function(deck) deck[sample(nrow(deck)), ]
shuffle_deck(deck) %>% head()
```

##3.implement start_game() function that shuffles deck

```{r}
### 2) implement start_game() function that shuffles deck, 
# deals 2 cards for you and dealer. and prints state
state <- function(mixed, dealer_hand, player_hand) {
## output
  cat("Dealer's hand:", fill = TRUE)
  print(dealer_hand, row.names = FALSE)
  print(paste0("Sum: ", sum(dealer_hand$value)))
  cat("Yours hand:", fill = TRUE)
  print(player_hand, row.names = FALSE)
  print(paste0("Sum: ", sum(player_hand$value)))
## chances
  if(sum(player_hand$value) %in% c(sum(dealer_hand$value):21)) {
    print("chances 100 %")
  } else if (sum(player_hand$value) > 21) {
    print("chances 0 %")
  } else {                        
    lrange <- sum(dealer_hand$value) - sum(player_hand$value)
    hrange <- 21 - sum(player_hand$value) 
    limit <- c(lrange:hrange)
    count <- sum(mixed$value %in% limit)
    ifelse(hrange - lrange > 10, 'The difference between sum of a player and dealer more than 10', 
           print(paste0("chances: ", (count/nrow(mixed))*100, " %")))
  }

}
```


```{r}
start_game <- function(deck) {
  mixed <- shuffle_deck(deck)
  dealer_hand <- mixed[c(1:2), ]
  mixed <- mixed[-c(1:2), ]
  player_hand <- mixed[c(1:2), ]
  mixed <- mixed[-c(1:2), ]
  state(mixed, dealer_hand, player_hand)
}
```

##3.implement deal() function that deals you a card and prints state

```{r}
### 3) implement deal() function that deals you a card and prints state
deal <- function() {
  card <- mixed[1,]
  player_hand <- rbind(player_hand, card)
  mixed <<- mixed[-c(1), ]
  state(mixed, dealer_hand, player_hand)
}
```

##4.implement stop_game() function that prints result: win or loose

```{r}
### 4) implement stop_game() function that prints result: win or loose
stop_game <- function() {
  ifelse(sum(player_hand$value) %in% c(sum(dealer_hand$value):21), 'win', 'lose')
}
```

##5.test one

```{r}
### 5) Test 1
start_game(deck)
deal()
stop_game()
```

##5.test two

```{r}
start_game(deck)
deal()
stop_game()
```

